development:
  adapter: postgresql
  encoding: unicode
  database: task_manager_development
  pool: 5
  username: postgres
  password: postgres
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: task_manager_test
  pool: 5
  username: postgres
  password: postgres
  host: localhost
